<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260303071433 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE add_product_history ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE add_product_history ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE app_user ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE app_user ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE app_user ALTER roles TYPE JSON USING roles::json');
        $this->addSql('ALTER TABLE category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE coupon ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE coupon ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE customer_order ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE customer_order ALTER subtotal DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER shipping_method DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER shipping_fee DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER discount_amount DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER payment_method DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_d3c0a4b2a76ed395 RENAME TO IDX_3B1CE6A3A76ED395');
        $this->addSql('ALTER TABLE order_item ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product ALTER stock DROP DEFAULT');
        $this->addSql('ALTER TABLE review ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE review ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE sub_category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE sub_category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE add_product_history ALTER id SET DEFAULT nextval(\'add_product_history_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE add_product_history ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE app_user ALTER id SET DEFAULT nextval(\'app_user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE app_user ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE app_user ALTER roles TYPE TEXT USING roles::text');
        $this->addSql('ALTER TABLE category ALTER id SET DEFAULT nextval(\'category_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE category ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE coupon ALTER id SET DEFAULT nextval(\'coupon_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE coupon ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE customer_order ALTER id SET DEFAULT nextval(\'customer_order_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE customer_order ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE customer_order ALTER subtotal SET DEFAULT 0');
        $this->addSql('ALTER TABLE customer_order ALTER shipping_method SET DEFAULT \'standard\'');
        $this->addSql('ALTER TABLE customer_order ALTER shipping_fee SET DEFAULT 0');
        $this->addSql('ALTER TABLE customer_order ALTER discount_amount SET DEFAULT 0');
        $this->addSql('ALTER TABLE customer_order ALTER payment_method SET DEFAULT \'card\'');
        $this->addSql('ALTER INDEX idx_3b1ce6a3a76ed395 RENAME TO idx_d3c0a4b2a76ed395');
        $this->addSql('ALTER TABLE messenger_messages ALTER id TYPE INT');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE order_item ALTER id SET DEFAULT nextval(\'order_item_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE order_item ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE product ALTER id SET DEFAULT nextval(\'product_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE product ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE product ALTER stock SET DEFAULT 0');
        $this->addSql('ALTER TABLE review ALTER id SET DEFAULT nextval(\'review_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE review ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE sub_category ALTER id SET DEFAULT nextval(\'sub_category_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE sub_category ALTER id DROP IDENTITY');
    }
}
