<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260303072519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE add_product_history ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE add_product_history ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE add_product_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE app_user ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE app_user ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE app_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE app_user ALTER roles TYPE JSON USING roles::json');
        $this->addSql('ALTER TABLE category ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE category ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE coupon ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE coupon ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE coupon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE customer_order ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE customer_order ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE customer_order ALTER subtotal DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER shipping_method DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER shipping_fee DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER discount_amount DROP DEFAULT');
        $this->addSql('ALTER TABLE customer_order ALTER payment_method DROP DEFAULT');
        $this->addSql('ALTER INDEX IF EXISTS idx_d3c0a4b2a76ed395 RENAME TO IDX_3B1CE6A3A76ED395');
        $this->addSql('ALTER TABLE order_item ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE order_item ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE product ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product ALTER stock DROP DEFAULT');
        $this->addSql('ALTER TABLE review ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE review ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE sub_category ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE sub_category ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE sub_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE messenger_messages ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE messenger_messages ALTER COLUMN id TYPE BIGINT');
        $this->addSql('ALTER TABLE messenger_messages ALTER COLUMN id DROP DEFAULT');
        $this->addSql('ALTER TABLE messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE add_product_history ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE add_product_history ALTER COLUMN id SET DEFAULT nextval(\'add_product_history_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE app_user ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE app_user ALTER COLUMN id SET DEFAULT nextval(\'app_user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE app_user ALTER roles TYPE TEXT USING roles::text');
        $this->addSql('ALTER TABLE category ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE category ALTER COLUMN id SET DEFAULT nextval(\'category_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE coupon ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE coupon ALTER COLUMN id SET DEFAULT nextval(\'coupon_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE customer_order ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE customer_order ALTER COLUMN id SET DEFAULT nextval(\'customer_order_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE customer_order ALTER subtotal SET DEFAULT 0');
        $this->addSql('ALTER TABLE customer_order ALTER shipping_method SET DEFAULT \'standard\'');
        $this->addSql('ALTER TABLE customer_order ALTER shipping_fee SET DEFAULT 0');
        $this->addSql('ALTER TABLE customer_order ALTER discount_amount SET DEFAULT 0');
        $this->addSql('ALTER TABLE customer_order ALTER payment_method SET DEFAULT \'card\'');
        $this->addSql('ALTER INDEX IF EXISTS idx_3b1ce6a3a76ed395 RENAME TO idx_d3c0a4b2a76ed395');
        $this->addSql('ALTER TABLE messenger_messages ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE messenger_messages ALTER COLUMN id TYPE INT');
        $this->addSql('ALTER TABLE messenger_messages ALTER COLUMN id SET DEFAULT nextval(\'messenger_messages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE order_item ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE order_item ALTER COLUMN id SET DEFAULT nextval(\'order_item_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE product ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE product ALTER COLUMN id SET DEFAULT nextval(\'product_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE product ALTER stock SET DEFAULT 0');
        $this->addSql('ALTER TABLE review ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE review ALTER COLUMN id SET DEFAULT nextval(\'review_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE sub_category ALTER COLUMN id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE sub_category ALTER COLUMN id SET DEFAULT nextval(\'sub_category_id_seq\'::regclass)');
    }
}
